# default
quarkus.container-image.build=false
quarkus.http.root-path=/docs

docs.root.path=${DocTechHome:/tmp}

# JVM image builds
%jib.quarkus.container-image.build=true
%jib.quarkus.container-image.builder=jib

# Native/custom builds
%podman.quarkus.container-image.build=true
%podman.quarkus.container-image.builder=podman
